name: MiniMOTD
version: $version
main: xyz.jpenilla.minimotd.bukkit.MiniMOTDPlugin
folia-supported: true
description: $description
authors:
  - jmp
website: $website
commands:
  minimotd:
    description: MiniMOTD Command
    permission: minimotd.admin
    usage: /minimotd help
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ViaVersion
